{% macro run_recipe(autopie_prefix, recipe_type, ingredients, target_fact, source_fact) %}

{% if not autopie_prefix|length>0%}{% set autopie_prefix = env_var('AUTOPIE_PREFIX', 'autopie.') %}{% endif -%}

{# /* compile the recipe into SQL */ #}
{% if recipe_type == 'collect_fact' %}{% set compiled_sql = compile_recipe_collect_fact(autopie_prefix, ingredients, target_fact) -%}
{% elif recipe_type == 'collect_union' %}{% set compiled_sql = compile_recipe_collect_union(autopie_prefix, ingredients, target_fact) -%}
{% elif recipe_type == 'blend_join' %}{% set compiled_sql = compile_recipe_blend_join(autopie_prefix, ingredients, target_fact, source_fact) -%}
{% elif recipe_type == 'blend_window' %}{% set compiled_sql = compile_recipe_blend_window(autopie_prefix, ingredients, target_fact) -%}
{% elif recipe_type == 'chop_rollup' %}{% set compiled_sql = compile_recipe_chop_rollup(autopie_prefix, ingredients, target_fact) -%}
{% elif recipe_type == 'chop_state' %}{% set compiled_sql = compile_recipe_chop_state(autopie_prefix, ingredients,target_fact, source_fact) -%}
{% elif recipe_type == 'chop_last' %}{% set compiled_sql = compile_recipe_chop_last(autopie_prefix, ingredients,target_fact, source_fact) -%}
{% elif recipe_type == 'chop_range' %}{% set compiled_sql = compile_recipe_chop_range(autopie_prefix, ingredients,target_fact, source_fact) -%}
{% endif -%}

{# /* print sql in debug or info mode */ #}
{% if env_var('AUTOPIE_RUN_MODE', 'INFO') == 'DEBUG' or env_var('AUTOPIE_RUN_MODE', 'DEBUG') == 'INFO' -%}
{{ log(compiled_sql, info=True) }}
{% endif -%}

{# /* run the SQL generated by compiler in DEBUG or RUN mode */ #}
{% if env_var('AUTOPIE_RUN_MODE', 'INFO') == 'DEBUG' or env_var('AUTOPIE_RUN_MODE', 'DEBUG') == 'RUN' -%}
{% set results = run_query(compiled_sql) -%}
{% endif -%}

{# /* do some tests on the objects previous step executed */ #}
{% set sql %}
{% if recipe_type in ('collect_union', 'chop_rollup', 'collect_fact') -%}
select row_number() over (order by autopie_run_id desc) run_sequence, count(*) count_records 
  from {{autopie_prefix}}obj_fact_{{target_fact['id']}}
group by autopie_run_id
order by 1 
limit 5;
{% else -%}
select row_number() over (order by autopie_run_id desc) run_sequence, count(*) count_records 
  from {{autopie_prefix}}obj_fact_{{target_fact}}
group by autopie_run_id
order by 1
limit 5;
{% endif -%}
{% endset %}

{% if env_var('AUTOPIE_RUN_MODE', 'INFO') != 'INFO' %}
{% set results = run_query(sql) %}
{# do results.print_table() #}
{% endif %}

{% endmacro %}
